services:
  - type: web
    name: api-arkia
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright
      - key: AUTOMATION_URL
        sync: false
      - key: AUTOMATION_USER
        sync: false
      - key: AUTOMATION_PASS
        sync: false
